#########################################################################
# Title:            Community: flaresolverr                             #
# Author(s):        Satz                                                #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  flaresolverr/flaresolverr                           #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Stop and remove any existing container
  docker_container:
    name: flaresolverr
    state: absent

- name: Create and start container
  docker_container:
    name: flaresolverr
    image: 'flaresolverr/flaresolverr:latest'
    pull: yes
    ports:
      - '8191:8191'
    env:
      TZ: '{{ tz }}'
      UID: '{{ uid }}'
      GID: '{{ gid }}'
      LOG_LEVEL: 'info'
    networks:
      - name: cloudbox
        aliases:
          - flaresolverr
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
